---
services:
  server:
    image: yvv4docker/speedtest-macos:latest
    container_name: server
    hostname: server
    environment:
      - TCP_SERVER_HOST=0.0.0.0
      - TCP_SERVER_PORT=1543
      - TCP_SERVER_BUF_SIZE=1024
      - TCP_SERVER_METRICS_ADDR=0.0.0.0:8080
    ports:
      - "1543:1543"
      - "8080:8080"
    networks:
      - speedtest-network
    entrypoint: ./speedtest-tcp -t server

  client:
    image: yvv4docker/speedtest-macos:latest
    container_name: client
    hostname: client
    environment:
      - TCP_SERVER_HOST=server
      - TCP_SERVER_PORT=1543
      - TCP_SERVER_BUF_SIZE=1024
      - TCP_SERVER_METRICS_ADDR=8080
    networks:
      - speedtest-network
    entrypoint: ./speedtest-tcp -t client

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - speedtest-network
    depends_on:
      - server

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - speedtest-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./configs/grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./configs/grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

networks:
  speedtest-network:
    driver: bridge