---
services:
  server:
    image: yvv4docker/speedtest:latest
    container_name: server
    hostname: server
    env_file: .env
    ports:
      - "1543:1543"
      - "8080:8080"
    networks:
      - speedtest-network
    entrypoint: ./speedtest-tcp -t server

  client:
    image: yvv4docker/speedtest:latest
    container_name: client
    hostname: client
    env_file: .env
    networks:
      - speedtest-network
    entrypoint: ./speedtest-tcp -t client

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - speedtest-network
    depends_on:
      - server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - speedtest-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./configs/grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./configs/grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

networks:
  speedtest-network:
    driver: bridge