{
 "title": "Send & Receive",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      { "expr": "go_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Mem sys bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "go_memstats_sys_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Heap alloc bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Heap objects",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "targets": [
      { "expr": "go_memstats_heap_objects", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GC last time seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "delta(go_memstats_last_gc_time_seconds[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Speedtest - TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Receive",
   "type": "timeseries",
   "description": "Receive bytes from client",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(tcp_server_bytes_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "timeseries",
   "description": "Send bytes via tcp server",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(tcp_server_bytes_sent_total[1m])"
    }
   ]
  }
 ]
}